apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: D:\Projects\docker-ddb-kubernetes\kompose-windows-amd64.exe convert
      --controller daemonSet -f .\docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
    net.project-fifo.ddb.cluster.name: ddb
  creationTimestamp: null
  labels:
    io.kompose.service: coordinator
  name: coordinator
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: coordinator
    spec:
      containers:
      - env:
        - name: BUCKETS
          value: InfluxDB 1s 1d 1d 30s;graphite 1s 1d 1d 30s;syslog 1s 1d 1d 30s;promwriter
            1s 1d 1d 30s
        - name: CLUSTER_NAME
          value: ddb
        - name: RING_SIZE
          value: "8"
        image: projectfifo/ddb
        name: coordinator
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
