apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: D:\Projects\docker-ddb-kubernetes\kompose-windows-amd64.exe convert
      --controller daemonSet -f .\docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
    net.project-fifo.dfe.cluster.name: ddb
  creationTimestamp: null
  labels:
    io.kompose.service: fe
  name: fe
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fe
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: ddb
        - name: COORDINATOR_NODE
          value: coordinator
        - name: DB_NODE
          value: db
        - name: PG_NODE
          value: pg
        image: projectfifo/dfe
        name: fe
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
