apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: D:\Projects\docker-ddb-kubernetes\kompose-windows-amd64.exe convert
      --controller daemonSet -f .\docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - env:
        - name: GF_PATHS_PLUGINS
          value: /plugins
        image: projectfifo/grafana
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
      volumeMounts:
        - mountPath: /plugins
          name: plugins
      restartPolicy: Always
      volumes:
        - name: plugins
          persistentVolumeClaim:
            claimName: grafana-plugins
  volumeClaimTemplates:
    - metadata:
        name: plugins
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
