apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: D:\Projects\docker-ddb-kubernetes\kompose-windows-amd64.exe convert
      --controller daemonSet -f .\docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: pg
  name: pg
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pg
    spec:
      containers:
      - image: projectfifo/metric_metadata
        name: pg
        resources: {}
      restartPolicy: Always
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
