apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: D:\Projects\docker-ddb-kubernetes\kompose-windows-amd64.exe convert
      --controller daemonSet -f .\docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
    net.project-fifo.dfe.cluster.name: ddb
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: ddb
        - name: DB_NODE
          value: db
        - name: PG_NODE
          value: pg
        image: projectfifo/ddb_proxy
        name: proxy
        ports:
        - containerPort: 8086
        - containerPort: 2003
        - containerPort: 4242
        - containerPort: 9999
        - containerPort: 1234
        resources: {}
      restartPolicy: Always
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
