- name: Import Erlang Solutions repo key
  command: rpm --import https://packages.erlang-solutions.com/rpm/erlang_solutions.asc
- name: Add Erlang Solutions repository
  template:
    src: templates/erlang.repo.j2
    dest: /etc/yum.repos.d/erlang.repo
    owner: root
    group: root
    mode: 0644
    force: yes
- name: Install Erlang Solutions packages
  yum:
    name: "erlang"
    state: present
    update_cache: yes
