apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Projects\docker-ddb-kubernetes\kompose-windows-amd64.exe convert
      --controller daemonSet -f .\docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
    net.project-fifo.ddb.cluster.name: ddb
  creationTimestamp: null
  labels:
    io.kompose.service: coordinator
  name: coordinator
spec:
  ports:
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    io.kompose.service: coordinator
status:
  loadBalancer: {}
