apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: D:\Projects\docker-ddb-kubernetes\kompose-windows-amd64.exe convert
      --controller daemonSet -f .\docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
    net.project-fifo.ddb.cluster.name: ddb
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: CLUSTER_NAME
          value: ddb
        - name: COORDINATOR_NODE
          value: coordinator
        - name: RING_SIZE
          value: "8"
        image: projectfifo/ddb
        name: db
        ports:
        - containerPort: 5555
        resources: {}        
        volumeMounts:
          - mountPath: "/data"
            name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-data
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
